import {
  cmd,
  drill,
  h2,
  note,
  p,
  ul,
  type HandbookPage,
} from "./types";

function drillPage(
  slug: string,
  num: string,
  title: string,
  minutes: number,
  summary: string,
  symptom: string,
  commands: [string, string][],
  expected: string,
  cause: string,
): HandbookPage {
  return {
    slug,
    part: "7",
    num,
    title,
    summary,
    core: true,
    minutes,
    blocks: [
      p(symptom),
      h2("Commands, in order"),
      ...commands.map(([c, w]) => cmd(c, w)),
      drill(minutes, expected, cause),
      note("Timer is a coach, not a grade. Talk out loud like the live CLI test."),
    ],
  };
}

export const part7: HandbookPage[] = [
  drillPage(
    "drill-cameras-no-net",
    "D1",
    "Box has internet, cameras don’t",
    3,
    "Uplink works. Camera VLAN does not. Split the NICs.",
    "Symptom: you can SSH to the edge box from the office VLAN and `curl` the vendor cloud. Every camera is grey. The tech on site says “the internet is fine”.",
    [
      ["ip -br a", "How many NICs have addresses? Which subnet is the uplink vs the cameras?"],
      ["ip r", "Is there a route to the camera prefix, or only a default out the WAN NIC?"],
      ["ip neigh show", "Any camera MACs learned? Empty neigh on that VLAN = you are not on their L2."],
      ["ping -c 2 <camera-ip-or-gw>", "If this fails but 8.8.8.8 works, stop talking about the internet."],
    ],
    "Uplink NIC has a default route. Camera NIC is DOWN, unplugged, or on the wrong subnet / missing address. `ip neigh` empty on the camera interface.",
    "The box has two networks. Internet on NIC A does not imply L2/L3 to cameras on NIC B.",
  ),
  drillPage(
    "drill-dashboard-empty",
    "D2",
    "Cameras have IP, dashboard empty",
    3,
    "L3 is fine. The app is not.",
    "Symptom: you ping three cameras. The dashboard shows placeholders. Someone already “rebooted the switch”.",
    [
      ["ping -c 1 <camera>", "Confirm L3 one more time so you do not argue facts."],
      ["df -h", "Recording nodes die silently at 100%."],
      ["docker ps -a", "Is the dashboard / ingest container Up or Exited?"],
      ["docker logs --tail 100 NAME", "Bind error, disk, auth, or GPU — the log says which."],
    ],
    "Cameras reply to ping. `docker ps -a` shows `Exited` or a restart loop. Logs mention a crashed process or full disk. Not a VLAN problem.",
    "Reachability to the camera is necessary, not sufficient. The process that should ingest the stream is dead or wedged.",
  ),
  drillPage(
    "drill-ping-no-ssh",
    "D3",
    "Can ping IP, cannot SSH",
    3,
    "Host is alive. Port 22 is not yours yet.",
    "Symptom: `ping` to the box works. `ssh user@ip` times out or is refused. ICMP is not SSH.",
    [
      ["ping -c 3 <ip>", "L3 is up. Do not keep pinging."],
      ["ssh -v user@<ip>", "See whether the TCP handshake happens and which auth is offered."],
      ["sudo ss -tulpn | grep 22", "On console / jump: is sshd listening, and on which address?"],
      ["sudo ufw status verbose", "Host firewall dropping 22 after a “harden the box” session."],
    ],
    "`ss` shows no `:22` or ufw/SG denies it, or sshd bound to 127.0.0.1 only. Verbose SSH stops before `Offering public key`.",
    "ICMP success only proves ping. SSH needs a listener, a path to that port, and a matching key or password.",
  ),
  drillPage(
    "drill-dhcp-exhausted",
    "D4",
    "DHCP exhausted",
    3,
    "New camera, no IP. Old ones are fine.",
    "Symptom: a replacement camera never comes online. The last 40 cameras are still recording. Switch port is up, PoE is on.",
    [
      ["sudo timeout 15 tcpdump -i any -n port 67 or port 68", "Discovers with no offers = server or pool, not the NIC."],
      ["ip -br a", "From the box: do *you* still have a lease on that VLAN?"],
      ["ip neigh", "Do you see the new MAC? If yes, it may have a link-local only."],
    ],
    "tcpdump shows DHCP Discover, no Offer. Existing leases still ping. Switch CAM has the new MAC on the right VLAN.",
    "The pool is empty or the relay/server is down. Linux on the NVR cannot invent leases — take it to whoever owns DHCP.",
  ),
  drillPage(
    "drill-no-default-route",
    "D5",
    "Default route missing",
    2,
    "On-LAN works. The world does not.",
    "Symptom: you can ping the gateway and other closet IPs. `ping 8.8.8.8` fails. The dashboard in the cloud is unreachable. Someone “set a static”.",
    [
      ["ip r", "Look for `default via`. It is either missing or pointing at a former installer laptop."],
      ["ip route get 8.8.8.8", "Kernel will tell you it has nowhere to send this."],
      ["ping -c 2 <gateway>", "Connected route is fine — do not rebuild the VLAN."],
    ],
    "`ip r` has connected routes only. No `default via`. Gateway itself pings.",
    "Static IP was applied without a default route (or netplan `routes:` was omitted). LAN is not internet.",
  ),
  drillPage(
    "drill-dns-broken",
    "D6",
    "DNS broken",
    2,
    "Numbers work. Names do not.",
    "Symptom: `ping 8.8.8.8` is clean. `curl https://apt.ubuntu.com` fails. The tech says “the internet is down again”.",
    [
      ["ping -c 2 8.8.8.8", "Path is fine."],
      ["cat /etc/resolv.conf && resolvectl status", "Stub vs real nameservers. Empty or 127.0.0.9 is a clue."],
      ["dig example.com @1.1.1.1", "Bypass local resolver."],
      ["dig example.com", "What the box will actually use."],
    ],
    "ICMP to an IP works. `dig @1.1.1.1` works. Unscoped `dig` and `getent hosts` fail. resolvectl has no useful upstream.",
    "Routing is fine. The resolver config is empty, looped, or pointing at a dead DC DNS.",
  ),
  drillPage(
    "drill-docker-exited",
    "D7",
    "Docker container exited",
    3,
    "The unit of work is a container. It is not running.",
    "Symptom: box is pingable, disk is not full, cameras ping, dashboard 502. `docker ps` looks suspiciously tidy.",
    [
      ["docker ps -a", "Find Exited. Note the NAME and status code."],
      ["docker logs --tail 100 NAME", "Crash reason. Read the bottom."],
      ["df -h", "If logs say no space, believe them."],
      ["docker restart NAME", "Only after you know it will not immediately exit again."],
    ],
    "`docker ps -a` shows `Exited (1)` (or similar). Logs have a traceback, missing file, or bind error. `docker ps` without `-a` hid it.",
    "The application process is the container. Restart is allowed once you have the last 100 log lines in the ticket.",
  ),
  drillPage(
    "drill-disk-full",
    "D8",
    "Disk 100%",
    2,
    "Every daemon looks haunted. It is the filesystem.",
    "Symptom: SSH is slow or hangs after password. Docker will not pull. Recordings stopped at 02:14. Nobody changed the network.",
    [
      ["df -h", "100% on `/` or the recording mount. Stop here first."],
      ["df -i", "Inodes can be full too."],
      ["sudo du -xh / --max-depth=2 | sort -h | tail", "Who ate it — logs, docker, recordings."],
      ["lsblk", "Did a data disk fail to remount so everything spilled onto `/`?"],
    ],
    "`df -h` shows 100% used. `du` names `/var/lib/docker` or the recording path. Network commands are red herrings.",
    "A full disk fails writes; apps then fail in unrelated-looking ways. Free space before you restart anything.",
  ),
  drillPage(
    "drill-iface-rename",
    "D9",
    "Interface name changed after reboot",
    3,
    "ens18 vs eth0. netplan is talking to a ghost.",
    "Symptom: after a kernel or hardware change, the box has no IP. Netplan still says `eth0`. `ip -br a` shows `ens18` DOWN or unconfigured.",
    [
      ["ip -br a", "What names exist *now*."],
      ["ls /etc/netplan && sudo cat /etc/netplan/*.yaml", "What name the YAML still loves."],
      ["networkctl status", "Whether networkd is waiting on a missing NIC."],
    ],
    "YAML references `eth0` (or `ens18`) that is not in `ip -br a`. A different name is present with no address. This started after reboot, not after a VLAN change.",
    "Predictable naming assigned a new name. Persist by editing netplan to the live name (or a MAC match), then `netplan try`.",
  ),
  {
    slug: "drill-link-amber",
    part: "7",
    num: "D10",
    title: "Tech on phone: “link light amber”",
    summary: "Physical plant. Your Linux is a bystander.",
    core: true,
    minutes: 2,
    blocks: [
      p(
        "Symptom: on-site tech says the camera (or the drop) has an **amber** link light, or no light. They want you to “restart the server”.",
      ),
      h2("Commands, in order"),
      cmd(
        "ip -br link",
        "On the box: if this is the box’s own NIC, look for LOWER_UP. If this is a camera, Linux on the NVR cannot see that light.",
      ),
      ul([
        "Ask: **device, color, blinking, both ends.** Amber often means 100 Mbps or a negotiation consolation prize — or the vendor’s “no PoE” LED. You need the switch view.",
        "Ask them to read the **switch port**: status, speed, PoE. That is the source of truth.",
        "If it is the edge box NIC: reseat, known-good cable, different port, then `ip link show`.",
        "If it is a camera: you are in switch land. VLAN, PoE budget, shorted cable. Do not `docker restart`.",
      ]),
      drill(
        2,
        "You never opened NVIDIA docs. You either fixed a cable/port or you told them the amber light is not a Linux process.",
        "Link lights are L1. Restarting a container does not paint LEDs. Say it is the switch or the cable, and mean it.",
      ),
    ],
  },
];
